#!/usr/bin/env node
// @conciar/create-vue-shop — scaffold a Conciar-compatible Vue storefront.
// Zero runtime dependencies (Node built-ins only).
//
// Interactive:    npm create @conciar/vue-shop my-shop
// Non-interactive: create-vue-shop my-shop --api-url https://api.conciar.com \
//                    --api-key KEY --channel CH --name "My Shop"
import {
  existsSync, mkdirSync, readdirSync, statSync,
  copyFileSync, renameSync, readFileSync, writeFileSync,
} from 'node:fs'
import { join, resolve, basename, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createInterface } from 'node:readline/promises'
import { stdin as input, stdout as output, argv, exit, cwd } from 'node:process'

const HERE = dirname(fileURLToPath(import.meta.url))
const TEMPLATE_DIR = join(HERE, 'template')
// Never copy these from the template into a generated project.
const SKIP = new Set(['node_modules', 'dist', '.git', '.env', '.env.local', '.DS_Store'])

const c = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  cyan: '\x1b[36m', green: '\x1b[32m', red: '\x1b[31m', yellow: '\x1b[33m',
}
const b = (s) => `${c.bold}${s}${c.reset}`

// Tiny arg parser: positional args + `--flag value` / `--flag=value` / `--bool`.
function parseArgs(args) {
  const out = { _: [] }
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a.startsWith('--')) {
      const key = a.slice(2)
      if (key.includes('=')) { const [k, ...v] = key.split('='); out[k] = v.join('=') }
      else if (i + 1 < args.length && !args[i + 1].startsWith('--')) { out[key] = args[++i] }
      else out[key] = true
    } else out._.push(a)
  }
  return out
}

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(src)) {
    if (SKIP.has(entry)) continue
    const s = join(src, entry)
    const d = join(dest, entry)
    if (statSync(s).isDirectory()) copyDir(s, d)
    else copyFileSync(s, d)
  }
}

// Coerce a project name into a valid npm package name.
function toPackageName(name) {
  const slug = String(name).trim().toLowerCase().replace(/[^a-z0-9-~._]+/g, '-').replace(/^-+|-+$/g, '')
  return slug || 'conciar-shop'
}

async function main() {
  console.log(`\n  ${b('Create a Conciar shop')} ${c.dim}(@conciar/create-vue-shop)${c.reset}\n`)

  if (!existsSync(TEMPLATE_DIR)) {
    console.error(`${c.red}✖ Template not found at ${TEMPLATE_DIR}${c.reset}`)
    exit(1)
  }

  const args = parseArgs(argv.slice(2))
  // Prompt only on a real TTY; otherwise (CI / piped) take flags or defaults.
  const interactive = Boolean(input.isTTY) && !args.yes
  const rl = interactive ? createInterface({ input, output }) : null

  const ask = async (label, def) => {
    if (!rl) return def ?? ''
    const hint = def ? ` ${c.dim}(${def})${c.reset}` : ''
    const answer = (await rl.question(`  ${label}${hint}: `)).trim()
    return answer || def || ''
  }
  // Use a flag if supplied, else prompt/default.
  const field = async (flag, label, def) =>
    args[flag] != null && args[flag] !== true ? String(args[flag]) : ask(label, def)

  try {
    const target = args._[0] || (await ask('Project directory', 'my-conciar-shop')) || 'my-conciar-shop'
    const dest = resolve(cwd(), target)

    if (existsSync(dest) && readdirSync(dest).length > 0) {
      throw new Error(`${dest} already exists and is not empty.`)
    }

    const projectName = await field('name', 'Project name', basename(dest))
    const apiUrl = await field('api-url', 'Conciar API base URL', 'https://api.conciar.com')
    const apiKey = await field('api-key', 'Conciar Connect API key', '')
    const channelKey = await field('channel', 'Conciar sales channel key', '')
    rl?.close()

    console.log(`\n  ${c.cyan}Scaffolding into ${dest}…${c.reset}`)
    copyDir(TEMPLATE_DIR, dest)

    // npm strips real .gitignore from published packages, so it ships as _gitignore.
    const shippedIgnore = join(dest, '_gitignore')
    if (existsSync(shippedIgnore)) renameSync(shippedIgnore, join(dest, '.gitignore'))

    // Set the package name.
    const pkgPath = join(dest, 'package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    pkg.name = toPackageName(projectName)
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

    // Write .env.local with the answers (gitignored — safe for the API key).
    const env = [
      '# Generated by @conciar/create-shop',
      '# Server-only (read by vite.config.ts proxy; never bundled into the browser):',
      `CONCIAR_API_URL=${apiUrl}`,
      `CONCIAR_API_KEY=${apiKey}`,
      `CONCIAR_SALES_CHANNEL_KEY=${channelKey}`,
      '',
      '# Browser-safe (VITE_ prefix). Any non-empty VITE_CONCIAR_API_URL disables mock mode.',
      `VITE_CONCIAR_API_URL=${apiUrl}`,
      'VITE_APP_URL=http://localhost:5173',
      '',
    ].join('\n')
    writeFileSync(join(dest, '.env.local'), env)

    const rel = target.startsWith('.') ? target : `./${target}`
    console.log(`\n  ${c.green}✓ Done!${c.reset} Your Conciar shop is ready.\n`)
    if (!apiKey) {
      console.log(`  ${c.yellow}! No API key set — fill in CONCIAR_API_KEY / CONCIAR_SALES_CHANNEL_KEY in ${rel}/.env.local${c.reset}\n`)
    }
    console.log('  Next steps:\n')
    console.log(`    ${b(`cd ${rel}`)}`)
    console.log(`    ${b('npm install')}`)
    console.log(`    ${b('npm run dev')}\n`)
    console.log(`  ${c.dim}Edit .env.local to point at your Conciar instance; tweak --color-primary in src/assets/main.css to rebrand.${c.reset}\n`)
  } catch (err) {
    rl?.close()
    console.error(`\n${c.red}✖ ${err?.message ?? err}${c.reset}\n`)
    exit(1)
  }
}

main()
